using API.Models.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace API.Models.Configuration
{
    public class CountryConfiguration : IEntityTypeConfiguration<Country>
    {
        public void Configure(EntityTypeBuilder<Country> builder)
        {
            builder.HasData(
                new Country() { CountryID = 1, CountryName = "Afghanistan", ISOCode = "AF" },
                new Country() { CountryID = 2, CountryName = "Albania", ISOCode = "AL" },
                new Country() { CountryID = 3, CountryName = "Algeria", ISOCode = "DZ" },
                new Country() { CountryID = 4, CountryName = "Andorra", ISOCode = "AD" },
                new Country() { CountryID = 5, CountryName = "Angola", ISOCode = "AO" },
                new Country() { CountryID = 6, CountryName = "Antigua and Barbuda", ISOCode = "AG" },
                new Country() { CountryID = 7, CountryName = "Argentina", ISOCode = "AR" },
                new Country() { CountryID = 8, CountryName = "Armenia", ISOCode = "AM" },
                new Country() { CountryID = 9, CountryName = "Australia", ISOCode = "AU" },
                new Country() { CountryID = 10, CountryName = "Austria", ISOCode = "AT" },
                new Country() { CountryID = 11, CountryName = "Azerbaijan", ISOCode = "AZ" },
                new Country() { CountryID = 12, CountryName = "Bahamas", ISOCode = "BS" },
                new Country() { CountryID = 13, CountryName = "Bahrain", ISOCode = "BH" },
                new Country() { CountryID = 14, CountryName = "Bangladesh", ISOCode = "BD" },
                new Country() { CountryID = 15, CountryName = "Barbados", ISOCode = "BB" },
                new Country() { CountryID = 16, CountryName = "Belarus", ISOCode = "BY" },
                new Country() { CountryID = 17, CountryName = "Belgium", ISOCode = "BE" },
                new Country() { CountryID = 18, CountryName = "Belize", ISOCode = "BZ" },
                new Country() { CountryID = 19, CountryName = "Benin", ISOCode = "BJ" },
                new Country() { CountryID = 20, CountryName = "Bhutan", ISOCode = "BT" },
                new Country() { CountryID = 21, CountryName = "Bolivia", ISOCode = "BO" },
                new Country() { CountryID = 22, CountryName = "Bosnia and Herzegovina", ISOCode = "BA" },
                new Country() { CountryID = 23, CountryName = "Botswana", ISOCode = "BW" },
                new Country() { CountryID = 24, CountryName = "Brazil", ISOCode = "BR" },
                new Country() { CountryID = 25, CountryName = "Brunei", ISOCode = "BN" },
                new Country() { CountryID = 26, CountryName = "Bulgaria", ISOCode = "BG" },
                new Country() { CountryID = 27, CountryName = "Burkina Faso", ISOCode = "BF" },
                new Country() { CountryID = 28, CountryName = "Burundi", ISOCode = "BI" },
                new Country() { CountryID = 29, CountryName = "Cabo Verde", ISOCode = "CV" },
                new Country() { CountryID = 30, CountryName = "Cambodia", ISOCode = "KH" },
                new Country() { CountryID = 31, CountryName = "Cameroon", ISOCode = "CM" },
                new Country() { CountryID = 32, CountryName = "Canada", ISOCode = "CA" },
                new Country() { CountryID = 33, CountryName = "Central African Republic", ISOCode = "CF" },
                new Country() { CountryID = 34, CountryName = "Chad", ISOCode = "TD" },
                new Country() { CountryID = 35, CountryName = "Chile", ISOCode = "CL" },
                new Country() { CountryID = 36, CountryName = "China", ISOCode = "CN" },
                new Country() { CountryID = 37, CountryName = "Colombia", ISOCode = "CO" },
                new Country() { CountryID = 38, CountryName = "Comoros", ISOCode = "KM" },
                new Country() { CountryID = 39, CountryName = "Congo (Congo-Brazzaville)", ISOCode = "CG" },
                new Country() { CountryID = 40, CountryName = "Congo (Congo-Kinshasa)", ISOCode = "CD" },
                new Country() { CountryID = 41, CountryName = "Costa Rica", ISOCode = "CR" },
                new Country() { CountryID = 42, CountryName = "Croatia", ISOCode = "HR" },
                new Country() { CountryID = 43, CountryName = "Cuba", ISOCode = "CU" },
                new Country() { CountryID = 44, CountryName = "Cyprus", ISOCode = "CY" },
                new Country() { CountryID = 45, CountryName = "Czechia", ISOCode = "CZ" },
                new Country() { CountryID = 46, CountryName = "Denmark", ISOCode = "DK" },
                new Country() { CountryID = 47, CountryName = "Djibouti", ISOCode = "DJ" },
                new Country() { CountryID = 48, CountryName = "Dominica", ISOCode = "DM" },
                new Country() { CountryID = 49, CountryName = "Dominican Republic", ISOCode = "DO" },
                new Country() { CountryID = 50, CountryName = "Ecuador", ISOCode = "EC" },
                new Country() { CountryID = 51, CountryName = "Egypt", ISOCode = "EG" },
                new Country() { CountryID = 52, CountryName = "El Salvador", ISOCode = "SV" },
                new Country() { CountryID = 53, CountryName = "Equatorial Guinea", ISOCode = "GQ" },
                new Country() { CountryID = 54, CountryName = "Eritrea", ISOCode = "ER" },
                new Country() { CountryID = 55, CountryName = "Estonia", ISOCode = "EE" },
                new Country() { CountryID = 56, CountryName = "Eswatini", ISOCode = "SZ" },
                new Country() { CountryID = 57, CountryName = "Ethiopia", ISOCode = "ET" },
                new Country() { CountryID = 58, CountryName = "Fiji", ISOCode = "FJ" },
                new Country() { CountryID = 59, CountryName = "Finland", ISOCode = "FI" },
                new Country() { CountryID = 60, CountryName = "France", ISOCode = "FR" },
                new Country() { CountryID = 61, CountryName = "Gabon", ISOCode = "GA" },
                new Country() { CountryID = 62, CountryName = "Gambia", ISOCode = "GM" },
                new Country() { CountryID = 63, CountryName = "Georgia", ISOCode = "GE" },
                new Country() { CountryID = 64, CountryName = "Germany", ISOCode = "DE" },
                new Country() { CountryID = 65, CountryName = "Ghana", ISOCode = "GH" },
                new Country() { CountryID = 66, CountryName = "Greece", ISOCode = "GR" },
                new Country() { CountryID = 67, CountryName = "Grenada", ISOCode = "GD" },
                new Country() { CountryID = 68, CountryName = "Guatemala", ISOCode = "GT" },
                new Country() { CountryID = 69, CountryName = "Guinea", ISOCode = "GN" },
                new Country() { CountryID = 70, CountryName = "Guinea-Bissau", ISOCode = "GW" },
                new Country() { CountryID = 71, CountryName = "Guyana", ISOCode = "GY" },
                new Country() { CountryID = 72, CountryName = "Haiti", ISOCode = "HT" },
                new Country() { CountryID = 73, CountryName = "Honduras", ISOCode = "HN" },
                new Country() { CountryID = 74, CountryName = "Hungary", ISOCode = "HU" },
                new Country() { CountryID = 75, CountryName = "Iceland", ISOCode = "IS" },
                new Country() { CountryID = 76, CountryName = "India", ISOCode = "IN" },
                new Country() { CountryID = 77, CountryName = "Indonesia", ISOCode = "ID" },
                new Country() { CountryID = 78, CountryName = "Iran", ISOCode = "IR" },
                new Country() { CountryID = 79, CountryName = "Iraq", ISOCode = "IQ" },
                new Country() { CountryID = 80, CountryName = "Ireland", ISOCode = "IE" },
                new Country() { CountryID = 81, CountryName = "Israel", ISOCode = "IL" },
                new Country() { CountryID = 82, CountryName = "Italy", ISOCode = "IT" },
                new Country() { CountryID = 83, CountryName = "Jamaica", ISOCode = "JM" },
                new Country() { CountryID = 84, CountryName = "Japan", ISOCode = "JP" },
                new Country() { CountryID = 85, CountryName = "Jordan", ISOCode = "JO" },
                new Country() { CountryID = 86, CountryName = "Kazakhstan", ISOCode = "KZ" },
                new Country() { CountryID = 87, CountryName = "Kenya", ISOCode = "KE" },
                new Country() { CountryID = 88, CountryName = "Kiribati", ISOCode = "KI" },
                new Country() { CountryID = 89, CountryName = "Korea, North", ISOCode = "KP" },
                new Country() { CountryID = 90, CountryName = "Korea, South", ISOCode = "KR" },
                new Country() { CountryID = 91, CountryName = "Kuwait", ISOCode = "KW" },
                new Country() { CountryID = 92, CountryName = "Kyrgyzstan", ISOCode = "KG" },
                new Country() { CountryID = 93, CountryName = "Laos", ISOCode = "LA" },
                new Country() { CountryID = 94, CountryName = "Latvia", ISOCode = "LV" },
                new Country() { CountryID = 95, CountryName = "Lebanon", ISOCode = "LB" },
                new Country() { CountryID = 96, CountryName = "Lesotho", ISOCode = "LS" },
                new Country() { CountryID = 97, CountryName = "Liberia", ISOCode = "LR" },
                new Country() { CountryID = 98, CountryName = "Libya", ISOCode = "LY" },
                new Country() { CountryID = 99, CountryName = "Liechtenstein", ISOCode = "LI" },
                new Country() { CountryID = 100, CountryName = "Lithuania", ISOCode = "LT" },
                new Country() { CountryID = 101, CountryName = "Luxembourg", ISOCode = "LU" },
                new Country() { CountryID = 102, CountryName = "Madagascar", ISOCode = "MG" },
                new Country() { CountryID = 103, CountryName = "Malawi", ISOCode = "MW" },
                new Country() { CountryID = 104, CountryName = "Malaysia", ISOCode = "MY" },
                new Country() { CountryID = 105, CountryName = "Maldives", ISOCode = "MV" },
                new Country() { CountryID = 106, CountryName = "Mali", ISOCode = "ML" },
                new Country() { CountryID = 107, CountryName = "Malta", ISOCode = "MT" },
                new Country() { CountryID = 108, CountryName = "Marshall Islands", ISOCode = "MH" },
                new Country() { CountryID = 109, CountryName = "Mauritania", ISOCode = "MR" },
                new Country() { CountryID = 110, CountryName = "Mauritius", ISOCode = "MU" },
                new Country() { CountryID = 111, CountryName = "Mexico", ISOCode = "MX" },
                new Country() { CountryID = 112, CountryName = "Micronesia", ISOCode = "FM" },
                new Country() { CountryID = 113, CountryName = "Moldova", ISOCode = "MD" },
                new Country() { CountryID = 114, CountryName = "Monaco", ISOCode = "MC" },
                new Country() { CountryID = 115, CountryName = "Mongolia", ISOCode = "MN" },
                new Country() { CountryID = 116, CountryName = "Montenegro", ISOCode = "ME" },
                new Country() { CountryID = 117, CountryName = "Morocco", ISOCode = "MA" },
                new Country() { CountryID = 118, CountryName = "Mozambique", ISOCode = "MZ" },
                new Country() { CountryID = 119, CountryName = "Myanmar", ISOCode = "MM" },
                new Country() { CountryID = 120, CountryName = "Namibia", ISOCode = "NA" },
                new Country() { CountryID = 121, CountryName = "Nauru", ISOCode = "NR" },
                new Country() { CountryID = 122, CountryName = "Nepal", ISOCode = "NP" },
                new Country() { CountryID = 123, CountryName = "Netherlands", ISOCode = "NL" },
                new Country() { CountryID = 124, CountryName = "New Zealand", ISOCode = "NZ" },
                new Country() { CountryID = 125, CountryName = "Nicaragua", ISOCode = "NI" },
                new Country() { CountryID = 126, CountryName = "Niger", ISOCode = "NE" },
                new Country() { CountryID = 127, CountryName = "Nigeria", ISOCode = "NG" },
                new Country() { CountryID = 128, CountryName = "North Macedonia", ISOCode = "MK" },
                new Country() { CountryID = 129, CountryName = "Norway", ISOCode = "NO" },
                new Country() { CountryID = 130, CountryName = "Oman", ISOCode = "OM" },
                new Country() { CountryID = 131, CountryName = "Pakistan", ISOCode = "PK" },
                new Country() { CountryID = 132, CountryName = "Palau", ISOCode = "PW" },
                new Country() { CountryID = 133, CountryName = "Palestine", ISOCode = "PS" },
                new Country() { CountryID = 134, CountryName = "Panama", ISOCode = "PA" },
                new Country() { CountryID = 135, CountryName = "Papua New Guinea", ISOCode = "PG" },
                new Country() { CountryID = 136, CountryName = "Paraguay", ISOCode = "PY" },
                new Country() { CountryID = 137, CountryName = "Peru", ISOCode = "PE" },
                new Country() { CountryID = 138, CountryName = "Philippines", ISOCode = "PH" },
                new Country() { CountryID = 139, CountryName = "Poland", ISOCode = "PL" },
                new Country() { CountryID = 140, CountryName = "Portugal", ISOCode = "PT" },
                new Country() { CountryID = 141, CountryName = "Qatar", ISOCode = "QA" },
                new Country() { CountryID = 142, CountryName = "Romania", ISOCode = "RO" },
                new Country() { CountryID = 143, CountryName = "Russia", ISOCode = "RU" },
                new Country() { CountryID = 144, CountryName = "Rwanda", ISOCode = "RW" },
                new Country() { CountryID = 145, CountryName = "Saint Kitts and Nevis", ISOCode = "KN" },
                new Country() { CountryID = 146, CountryName = "Saint Lucia", ISOCode = "LC" },
                new Country() { CountryID = 147, CountryName = "Saint Vincent and the Grenadines", ISOCode = "VC" },
                new Country() { CountryID = 148, CountryName = "Samoa", ISOCode = "WS" },
                new Country() { CountryID = 149, CountryName = "San Marino", ISOCode = "SM" },
                new Country() { CountryID = 150, CountryName = "Sao Tome and Principe", ISOCode = "ST" },
                new Country() { CountryID = 151, CountryName = "Saudi Arabia", ISOCode = "SA" },
                new Country() { CountryID = 152, CountryName = "Senegal", ISOCode = "SN" },
                new Country() { CountryID = 153, CountryName = "Serbia", ISOCode = "RS" },
                new Country() { CountryID = 154, CountryName = "Seychelles", ISOCode = "SC" },
                new Country() { CountryID = 155, CountryName = "Sierra Leone", ISOCode = "SL" },
                new Country() { CountryID = 156, CountryName = "Singapore", ISOCode = "SG" },
                new Country() { CountryID = 157, CountryName = "Slovakia", ISOCode = "SK" },
                new Country() { CountryID = 158, CountryName = "Slovenia", ISOCode = "SI" },
                new Country() { CountryID = 159, CountryName = "Solomon Islands", ISOCode = "SB" },
                new Country() { CountryID = 160, CountryName = "Somalia", ISOCode = "SO" },
                new Country() { CountryID = 161, CountryName = "South Africa", ISOCode = "ZA" },
                new Country() { CountryID = 162, CountryName = "South Sudan", ISOCode = "SS" },
                new Country() { CountryID = 163, CountryName = "Spain", ISOCode = "ES" },
                new Country() { CountryID = 164, CountryName = "Sri Lanka", ISOCode = "LK" },
                new Country() { CountryID = 165, CountryName = "Sudan", ISOCode = "SD" },
                new Country() { CountryID = 166, CountryName = "Suriname", ISOCode = "SR" },
                new Country() { CountryID = 167, CountryName = "Sweden", ISOCode = "SE" },
                new Country() { CountryID = 168, CountryName = "Switzerland", ISOCode = "CH" },
                new Country() { CountryID = 169, CountryName = "Syria", ISOCode = "SY" },
                new Country() { CountryID = 170, CountryName = "Taiwan", ISOCode = "TW" },
                new Country() { CountryID = 171, CountryName = "Tajikistan", ISOCode = "TJ" },
                new Country() { CountryID = 172, CountryName = "Tanzania", ISOCode = "TZ" },
                new Country() { CountryID = 173, CountryName = "Thailand", ISOCode = "TH" },
                new Country() { CountryID = 174, CountryName = "Timor-Leste", ISOCode = "TL" },
                new Country() { CountryID = 175, CountryName = "Togo", ISOCode = "TG" },
                new Country() { CountryID = 176, CountryName = "Tonga", ISOCode = "TO" },
                new Country() { CountryID = 177, CountryName = "Trinidad and Tobago", ISOCode = "TT" },
                new Country() { CountryID = 178, CountryName = "Tunisia", ISOCode = "TN" },
                new Country() { CountryID = 179, CountryName = "Turkey", ISOCode = "TR" },
                new Country() { CountryID = 180, CountryName = "Turkmenistan", ISOCode = "TM" },
                new Country() { CountryID = 181, CountryName = "Tuvalu", ISOCode = "TV" },
                new Country() { CountryID = 182, CountryName = "Uganda", ISOCode = "UG" },
                new Country() { CountryID = 183, CountryName = "Ukraine", ISOCode = "UA" },
                new Country() { CountryID = 184, CountryName = "United Arab Emirates", ISOCode = "AE" },
                new Country() { CountryID = 185, CountryName = "United Kingdom", ISOCode = "GB" },
                new Country() { CountryID = 186, CountryName = "United States", ISOCode = "US" },
                new Country() { CountryID = 187, CountryName = "Uruguay", ISOCode = "UY" },
                new Country() { CountryID = 188, CountryName = "Uzbekistan", ISOCode = "UZ" },
                new Country() { CountryID = 189, CountryName = "Vanuatu", ISOCode = "VU" },
                new Country() { CountryID = 190, CountryName = "Vatican City", ISOCode = "VA" },
                new Country() { CountryID = 191, CountryName = "Venezuela", ISOCode = "VE" },
                new Country() { CountryID = 192, CountryName = "Vietnam", ISOCode = "VN" },
                new Country() { CountryID = 193, CountryName = "Yemen", ISOCode = "YE" },
                new Country() { CountryID = 194, CountryName = "Zambia", ISOCode = "ZM" },
                new Country() { CountryID = 195, CountryName = "Zimbabwe", ISOCode = "ZW" }
            );
        }
    }

}
