// <auto-generated />
using System;
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(Progetto_FormativoContext))]
    partial class Progetto_FormativoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("API.Models.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"), 1L, 1);

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("Deprecated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("OriginalID")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("CustomerName", "Country")
                        .IsUnique()
                        .HasFilter("[CustomerName] IS NOT NULL AND [Country] IS NOT NULL");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("API.Models.Entities.CustomerInvoice", b =>
                {
                    b.Property<int>("CustomerInvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CustomerInvoiceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerInvoiceId"), 1L, 1);

                    b.Property<decimal?>("InvoiceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("SaleId")
                        .HasColumnType("int")
                        .HasColumnName("SaleID");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("CustomerInvoiceId");

                    b.HasIndex("SaleId");

                    b.ToTable("CustomerInvoices", (string)null);
                });

            modelBuilder.Entity("API.Models.Entities.CustomerInvoiceCost", b =>
                {
                    b.Property<int>("CustomerInvoiceCostsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CustomerInvoiceCostsID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerInvoiceCostsId"), 1L, 1);

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CustomerInvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerInvoiceID");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CustomerInvoiceCostsId");

                    b.HasIndex("CustomerInvoiceId");

                    b.ToTable("CustomerInvoiceCosts", (string)null);
                });

            modelBuilder.Entity("API.Models.Entities.Preference.CustomerDGV", b =>
                {
                    b.Property<int?>("CustomerDGVID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CustomerDGVID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("CustomerDGVID"), 1L, 1);

                    b.Property<bool?>("ShowCountry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("ShowDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("ShowID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("ShowName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("ShowOriginalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("ShowStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CustomerDGVID");

                    b.ToTable("CustomerDGVs", (string)null);
                });

            modelBuilder.Entity("API.Models.Entities.Preference.CustomerGroupSplit", b =>
                {
                    b.Property<int?>("CustomerGroupSplitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CustomerGroupSplitID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("CustomerGroupSplitID"), 1L, 1);

                    b.Property<int?>("Split1")
                        .HasColumnType("int");

                    b.Property<int?>("Split2")
                        .HasColumnType("int");

                    b.Property<int?>("Split3")
                        .HasColumnType("int");

                    b.Property<int?>("Split4")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CustomerGroupSplitID");

                    b.ToTable("CustomerGroupSplits", (string)null);
                });

            modelBuilder.Entity("API.Models.Entities.Preference.CustomerInvoiceCostDGV", b =>
                {
                    b.Property<int?>("CustomerInvoiceCostDGVID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CustomerInvoiceCostDGVID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("CustomerInvoiceCostDGVID"), 1L, 1);

                    b.Property<bool?>("ShowCost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("ShowID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("ShowInvoiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("ShowName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("ShowQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CustomerInvoiceCostDGVID");

                    b.ToTable("CustomerInvoiceCostDGVs", (string)null);
                });

            modelBuilder.Entity("API.Models.Entities.Preference.CustomerInvoiceDGV", b =>
                {
                    b.Property<int?>("CustomerInvoiceDGVID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CustomerInvoiceDGVID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("CustomerInvoiceDGVID"), 1L, 1);

                    b.Property<bool?>("ShowDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("ShowID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("ShowInvoiceAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("ShowSaleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("ShowStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CustomerInvoiceDGVID");

                    b.ToTable("CustomerInvoiceDGVs", (string)null);
                });

            modelBuilder.Entity("API.Models.Entities.Preference.FavouritePages", b =>
                {
                    b.Property<int?>("FavouritePageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FavouritePageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("FavouritePageID"), 1L, 1);

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("FavouritePageID");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("FavouritePages", (string)null);
                });

            modelBuilder.Entity("API.Models.Entities.Preference.SaleDGV", b =>
                {
                    b.Property<int?>("SaleDGVID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SaleDGVID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("SaleDGVID"), 1L, 1);

                    b.Property<bool?>("ShowBKNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("ShowBoL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("ShowCustomerCountry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("ShowCustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("ShowCustomerName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("ShowDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("ShowID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("ShowStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("ShowTotalRevenue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("SaleDGVID");

                    b.ToTable("SaleDGVs", (string)null);
                });

            modelBuilder.Entity("API.Models.Entities.Preference.SupplierDGV", b =>
                {
                    b.Property<int?>("SupplierDGVID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SupplierDGVID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("SupplierDGVID"), 1L, 1);

                    b.Property<bool?>("ShowCountry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("ShowDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("ShowID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("ShowName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("ShowOriginalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("ShowStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("SupplierDGVID");

                    b.ToTable("SupplierDGVs", (string)null);
                });

            modelBuilder.Entity("API.Models.Entities.Preference.SupplierGroupSplit", b =>
                {
                    b.Property<int?>("SupplierGroupSplitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SupplierGroupSplitID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("SupplierGroupSplitID"), 1L, 1);

                    b.Property<int?>("Split1")
                        .HasColumnType("int");

                    b.Property<int?>("Split2")
                        .HasColumnType("int");

                    b.Property<int?>("Split3")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("SupplierGroupSplitID");

                    b.ToTable("SupplierGroupSplits", (string)null);
                });

            modelBuilder.Entity("API.Models.Entities.Preference.SupplierInvoiceCostDGV", b =>
                {
                    b.Property<int?>("SupplierInvoiceCostDGVID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SupplierInvoiceCostDGVID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("SupplierInvoiceCostDGVID"), 1L, 1);

                    b.Property<bool?>("ShowCost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("ShowID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("ShowName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("ShowQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("ShowSupplierInvoiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("SupplierInvoiceCostDGVID");

                    b.ToTable("SupplierInvoiceCostDGVs", (string)null);
                });

            modelBuilder.Entity("API.Models.Entities.Preference.SupplierInvoiceDGV", b =>
                {
                    b.Property<int?>("SupplierInvoiceDGVID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SupplierInvoiceDGVID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("SupplierInvoiceDGVID"), 1L, 1);

                    b.Property<bool?>("ShowCountry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("ShowID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("ShowInvoiceAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("ShowInvoiceDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("ShowSaleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("ShowStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("ShowSupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("ShowSupplierName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("SupplierInvoiceDGVID");

                    b.ToTable("SupplierInvoiceDGVs", (string)null);
                });

            modelBuilder.Entity("API.Models.Entities.Preference.UserDGV", b =>
                {
                    b.Property<int?>("UserDGVID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserDGVID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("UserDGVID"), 1L, 1);

                    b.Property<bool?>("ShowEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("ShowID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool?>("ShowLastName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("ShowName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("ShowRoles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("UserDGVID");

                    b.ToTable("UserDGVs", (string)null);
                });

            modelBuilder.Entity("API.Models.Entities.Preference.UserFavouritePage", b =>
                {
                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<int?>("FavouritePageID")
                        .HasColumnType("int");

                    b.HasKey("UserID", "FavouritePageID");

                    b.HasIndex("FavouritePageID");

                    b.ToTable("UserFavouritePages", (string)null);
                });

            modelBuilder.Entity("API.Models.Entities.RefreshToken", b =>
                {
                    b.Property<int>("TokenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TokenID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TokenID"), 1L, 1);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime");

                    b.Property<string>("Token")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(MAX)");

                    b.Property<int>("UserID")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("TokenID");

                    b.HasIndex("UserID");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("API.Models.Entities.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"), 1L, 1);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("RoleName");

                    b.HasKey("RoleID");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("API.Models.Entities.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SaleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"), 1L, 1);

                    b.Property<string>("BoLnumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("BoLNumber");

                    b.Property<string>("BookingNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<DateTime?>("SaleDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("TotalRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SaleId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Sales", (string)null);
                });

            modelBuilder.Entity("API.Models.Entities.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SupplierID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"), 1L, 1);

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<bool?>("Deprecated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("OriginalID")
                        .HasColumnType("int");

                    b.Property<string>("SupplierName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("SupplierId");

                    b.HasIndex("SupplierName", "Country")
                        .IsUnique()
                        .HasFilter("[SupplierName] IS NOT NULL AND [Country] IS NOT NULL");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("API.Models.Entities.SupplierInvoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InvoiceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"), 1L, 1);

                    b.Property<decimal?>("InvoiceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("SaleId")
                        .HasColumnType("int")
                        .HasColumnName("SaleID");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("SupplierID");

                    b.HasKey("InvoiceId");

                    b.HasIndex("SaleId");

                    b.HasIndex("SupplierId");

                    b.ToTable("SupplierInvoices", (string)null);
                });

            modelBuilder.Entity("API.Models.Entities.SupplierInvoiceCost", b =>
                {
                    b.Property<int>("SupplierInvoiceCostsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SupplierInvoiceCostsID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierInvoiceCostsId"), 1L, 1);

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierInvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("SupplierInvoiceID");

                    b.HasKey("SupplierInvoiceCostsId");

                    b.HasIndex("SupplierInvoiceId");

                    b.ToTable("SupplierInvoiceCosts", (string)null);
                });

            modelBuilder.Entity("API.Models.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<byte[]>("PasswordHash")
                        .IsUnicode(false)
                        .HasColumnType("varbinary(MAX)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsUnicode(false)
                        .HasColumnType("varbinary(MAX)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("API.Models.Entities.UserRole", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.HasKey("UserID", "RoleID");

                    b.HasIndex("RoleID");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("API.Models.Procedures.ClassifySalesByProfit", b =>
                {
                    b.Property<string>("BoLNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Profit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SaleID")
                        .HasColumnType("int");

                    b.Property<string>("SaleMargins")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalSpent")
                        .HasColumnType("decimal(18,2)");

                    b.ToView(null);
                });

            modelBuilder.Entity("API.Models.Procedures.TotalAmountGainedPerCustomerInvoice", b =>
                {
                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomerInvoiceID")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SaleID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalGained")
                        .HasColumnType("decimal(18,2)");

                    b.ToView(null);
                });

            modelBuilder.Entity("API.Models.Procedures.TotalAmountSpentPerSupplierInvoice", b =>
                {
                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InvoiceID")
                        .HasColumnType("int");

                    b.Property<int?>("SaleID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SupplierID")
                        .HasColumnType("int");

                    b.Property<string>("SupplierName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalSpent")
                        .HasColumnType("decimal(18,2)");

                    b.ToView(null);
                });

            modelBuilder.Entity("API.Models.Procedures.TotalAmountSpentPerSuppliers", b =>
                {
                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Deprecated")
                        .HasColumnType("bit");

                    b.Property<int?>("OriginalID")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierID")
                        .HasColumnType("int");

                    b.Property<string>("SupplierName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalAmountInvoiced")
                        .HasColumnType("decimal(18,2)");

                    b.ToView(null);
                });

            modelBuilder.Entity("API.Models.Entities.CustomerInvoice", b =>
                {
                    b.HasOne("API.Models.Entities.Sale", "Sale")
                        .WithMany("CustomerInvoices")
                        .HasForeignKey("SaleId")
                        .HasConstraintName("sale_CustomerInvoices_fk");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("API.Models.Entities.CustomerInvoiceCost", b =>
                {
                    b.HasOne("API.Models.Entities.CustomerInvoice", "CustomerInvoice")
                        .WithMany("CustomerInvoiceCosts")
                        .HasForeignKey("CustomerInvoiceId")
                        .HasConstraintName("FK_CustomerInvoiceCosts_CustomerInvoices");

                    b.Navigation("CustomerInvoice");
                });

            modelBuilder.Entity("API.Models.Entities.Preference.UserFavouritePage", b =>
                {
                    b.HasOne("API.Models.Entities.Preference.FavouritePages", "FavouritePage")
                        .WithMany("UserFavourtitePages")
                        .HasForeignKey("FavouritePageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Entities.User", "User")
                        .WithMany("UserFavouritePages")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FavouritePage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Models.Entities.RefreshToken", b =>
                {
                    b.HasOne("API.Models.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Models.Entities.Sale", b =>
                {
                    b.HasOne("API.Models.Entities.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("customer_sales_fk");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("API.Models.Entities.SupplierInvoice", b =>
                {
                    b.HasOne("API.Models.Entities.Sale", "Sale")
                        .WithMany("SupplierInvoices")
                        .HasForeignKey("SaleId")
                        .HasConstraintName("sale_supplierInvoices_fk");

                    b.HasOne("API.Models.Entities.Supplier", "Supplier")
                        .WithMany("SupplierInvoices")
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("supplier_supplierInvoices_fk");

                    b.Navigation("Sale");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("API.Models.Entities.SupplierInvoiceCost", b =>
                {
                    b.HasOne("API.Models.Entities.SupplierInvoice", "SupplierInvoice")
                        .WithMany("SupplierInvoiceCosts")
                        .HasForeignKey("SupplierInvoiceId")
                        .HasConstraintName("SupplierInvoiceID_SupplierInvoiceCosts_fk");

                    b.Navigation("SupplierInvoice");
                });

            modelBuilder.Entity("API.Models.Entities.UserRole", b =>
                {
                    b.HasOne("API.Models.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Models.Entities.Customer", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("API.Models.Entities.CustomerInvoice", b =>
                {
                    b.Navigation("CustomerInvoiceCosts");
                });

            modelBuilder.Entity("API.Models.Entities.Preference.FavouritePages", b =>
                {
                    b.Navigation("UserFavourtitePages");
                });

            modelBuilder.Entity("API.Models.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("API.Models.Entities.Sale", b =>
                {
                    b.Navigation("CustomerInvoices");

                    b.Navigation("SupplierInvoices");
                });

            modelBuilder.Entity("API.Models.Entities.Supplier", b =>
                {
                    b.Navigation("SupplierInvoices");
                });

            modelBuilder.Entity("API.Models.Entities.SupplierInvoice", b =>
                {
                    b.Navigation("SupplierInvoiceCosts");
                });

            modelBuilder.Entity("API.Models.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserFavouritePages");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
